import AnchantoLogo from './assets/images/anchanto-removebg-preview.png'
import ByjusLogo from './assets/images/Byjus-Logo.png'
import CollegeduniaLogo from './assets/images/Collegedunia_Logo-removebg-preview.png'
export const workExpirienceData = [
  {
    id: 1,
    companyName: "Collegedunia",
    logo:CollegeduniaLogo,
    designation: "Frontend Developer (Intern)",
    startDate: "15-03-2021",
    endDate: "31-07-2021",
    current: false,
    location: "Gurgoan, Haryana (WFH)",
    skills: [
      "Next.Js",
      "Javascript",
      "SCSS",
      "Redux",
      "Cypress.io",
      "Git",
      "Github",
    ],
    tenure: "5 Months",
    description: [],
  },
  {
    id: 2,
    companyName: "Think & Learn Pvt. Ltd ( Byjus )",
    logo:ByjusLogo,
    designation: "Software Engineer",
    startDate: "10-06-2022",
    endDate: "NA",
    current: true,
    location: "Bangalore, Karnataka (WFH)",
    skills: [
      "React,Js",
      "Javascript",
      "SCSS",
      "Redux",
      "Redux-saga",
      "Typescript",
      "Next.js",
      "Kotlin",
      "Android Development",
      "Git",
      "Github",
    ],
    tenure:'2 Years',
    description: [],
  },
  {
    id: 3,
    companyName: "Anchanto",
    logo:AnchantoLogo,
    designation: "Software Developer Engineer (Intern)",
    startDate: "02-01-2022",
    endDate: "30-04-2022",
    current: false,
    location: "Pune, Maharashtra (WFH)",
    skills: [
      "React,Js",
      "Javascript",
      "SCSS",
      "Redux",
      "Cypress.io",
      "Git",
      "Github",
    ],
    tenure:'4 Months',
    description: [],
  },
];
